// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.example.services;

public interface EmployeeResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.EmployeeResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();

  /**
   * <code>string name = 2;</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string designation = 3;</code>
   * @return The designation.
   */
  java.lang.String getDesignation();
  /**
   * <code>string designation = 3;</code>
   * @return The bytes for designation.
   */
  com.google.protobuf.ByteString
      getDesignationBytes();
}
