t// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: employee.proto

package com.example.services;

public interface GetEmployeeRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.GetEmployeeRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   * @return The id.
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   * @return The bytes for id.
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
